### ISSUE TITLE
Need a better Readme

### ISSUE THREAD

**Issue by lap00zza** [lap00zza/catch_me#1]

**Comment by rafa-acioly** [comment]
can you explain what the package does?

**Comment by lap00zza** [comment]
@rafa-acioly its a silly little game 😄 with nyan cat background music

![](https://i.imgur.com/3GclP2f.gif)

**Comment by rafa-acioly** [comment]
it's a "try to catch"? hahahaha

**Comment by lap00zza** [comment]
xD yeah

**Comment by rafa-acioly** [comment]
#6 
i made a new `readme` and i improved the variable declaration! hope you like it.

**Comment by lap00zza** [comment]
its perfect :) thanks
