### ISSUE TITLE
add a level system

### ISSUE THREAD

**Issue by WEBhicham** [lap00zza/catch_me#2]
add a new mode "levels"

having levels in the game example:

*level 1 : click 10 times in 60 sec (smal; screen)
*level 2:  click 15 times in 60 sec( small screen)
*level 10:  click 20 times in 60 sec( big screen)
ect :)

**Comment by mattk410** [comment]
I will work on this

**Comment by thecouchcoder** [comment]
@mattk410 if you decide not to, I'd like to implement this - or I can help you if you'd like
