### ISSUE TITLE
Use a pop-up system instead of alert()

### ISSUE THREAD

**Issue by Swardu** [lap00zza/catch_me#21]
Keep in note that it needs to pause the game.

**Comment by iblancasa** [comment]
Ey, look at this library :D https://sweetalert.js.org/ and https://github.com/limonte/sweetalert2

**Comment by bennett-treptow** [comment]
@iblancasa That would be a quick fix using the alert system I implemented! Simply putting swal() in there instead of my makeshift modal window.

**Comment by TummanapallyAnuraag** [comment]
I have addressed this problem in my fork.Please have a look at my pull request.

**Comment by lap00zza** [comment]
Closed in 3fea9ed0cf3779d2fda622b6a944aa9709c4c666
