### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by Swardu** [lap00zza/catch_me#3]
Add a timer to see how fast you can score.

**Comment by tezansahu** [comment]
I wish to solve this issue. Pls let me know the details

**Comment by Swardu** [comment]
For now, it's a timer that counts up. Could be added as a div near the score div. 

It would be great if it supports milliseconds too, and a start/stop/reset method.

**Comment by rodrigocam** [comment]
I made a pull request with this feature, please take a look!

**Comment by thecouchcoder** [comment]
@GitHugop  If it were to be integrated with the level enhancement, it probably needs to be a timer that counts down. If you want me to implement this, please let me know.

**Comment by lap00zza** [comment]
For this to work with levels, a countdown timer will indeed be better. Since @rodrigocam already sent a PR for the timer, I accepted. 

@aes421 if you want, you can then change/improve it (or do it as part of #2 if matt decides not do it 😃 )

**Comment by thecouchcoder** [comment]
@lap00zza sure thing! I will wait a few days and see what Matt has first.

**Comment by abdullateef97** [comment]
can i still work on this
