### ISSUE TITLE
Query params

### ISSUE THREAD

**Issue by Swardu** [lap00zza/catch_me#5]
Query params would be really nice, you can share a link with your desired settings directly to your friends on social media and more.

Query params can be done for level difficulty, page/CSS design and future game features.

**Comment by Tohoma** [comment]
How are you hosting this project?

**Comment by akshitgrover** [comment]
@GitHugop what exactly will GET API do?

**Comment by lap00zza** [comment]
@akshitgrover @GitHugop's idea is to enable difficulty selection via query params. Something like `catch_me.com?difficulty=easy`. We don't need a get api. This can/will be done via js.

**Comment by Swardu** [comment]
@Tohoma For now, we are planing to host it on GitHub Pages.

**Comment by akshitgrover** [comment]
@lap00zza @GitHugop so need of Server Side Scripting?

**Comment by lap00zza** [comment]
no need :) it will be overkill for such a tiny project

**Comment by akshitgrover** [comment]
@lap00zza Sure.

**Comment by Tohoma** [comment]
@akshitgrover Where you supposed to  handle the issue? I didn't read the later comments on the issue before tackling the problem.

@GitHugop @lap00zza
