### ISSUE TITLE
Improve the styling

### ISSUE THREAD

**Issue by lap00zza** [lap00zza/catch_me#8]
It looks to plain right now. A few things I have in mind are:

- [ ] Change color of the gray box
- [ ] Make the score counter a bit fancy (probably some drop shadow and rounder border?)
- [ ] A better background maybe

**Comment by BharatKalluri** [comment]
Can I take this?
Any preferences as to what colours you like?

**Comment by lap00zza** [comment]
Anything is fine 😄 . And yeah sure. Issue is yours. You can send individual pr's for the 3 tasks or all at once. Your call.

**Comment by WEBhicham** [comment]
@BharatKalluri make it as terrible as can be. 
meaning people are going to play the game but hate looking at the game. 
but still having a good layout/style it self. 

like.. Organized Chaos :)
